##### LED ######
GET http://192.168.4.1/red/on
###
GET http://192.168.4.1/red/off
###
GET http://192.168.4.1/green/on
###
GET http://192.168.4.1/green/off
###
GET http://192.168.4.1/relay/on
###
GET http://192.168.4.1/relay/off
###
#### Temp & human
GET http://192.168.4.1/temp
###
GET http://192.168.4.1/hum
###
###### Control #####
GET http://192.168.4.1/control?led=red&status=on
###
GET http://192.168.4.1/control?led=red&status=off
### 
GET http://192.168.4.1/control?led=green&status=on
###
GET http://192.168.4.1/control?led=green&status=off
###
###### OLED TEXT ###########
GET http://192.168.4.1/oled?text=Hello World
###
GET http://192.168.4.1/oled?text=Nawasan
###
GET http://192.168.4.1/oled?text=